"""Audit metadata safety policy.

Audit metadata is always server-generated by trusted service code — never
derived from a request body, an ORM object, an exception, or `vars()`/
`__dict__`/`model_dump()`. This module is the single choke point every
service must pass constructed metadata through before it reaches
`AuditService`. Validation is recursive and rejects rather than sanitizes:
an unsafe payload never becomes a persisted (possibly redacted) row.
"""

from app.core.exceptions import UnsafeAuditMetadataException

MAX_KEYS_PER_LEVEL = 20
MAX_KEY_LENGTH = 100
MAX_STRING_VALUE_LENGTH = 500
MAX_NESTING_DEPTH = 2  # top-level dict (depth 1) + one nested dict (depth 2)

# Checked case-insensitively against every key at every nesting level.
_FORBIDDEN_KEYS = frozenset(
    {
        "authorization",
        "password",
        "passwd",
        "secret",
        "secret_key",
        "secretkey",
        "token",
        "access_token",
        "refresh_token",
        "api_key",
        "apikey",
        "cookie",
        "set-cookie",
        "set_cookie",
        "database_url",
        "db_url",
        "private_key",
        "privatekey",
    }
)


def validate_metadata(metadata: dict | None) -> dict:
    """Validate server-generated audit metadata, raising if unsafe.

    Returns the same dict unchanged on success. Raises
    `UnsafeAuditMetadataException` on any policy violation. `None` is
    normalized to an empty dict.
    """
    if metadata is None:
        return {}

    if not isinstance(metadata, dict):
        raise UnsafeAuditMetadataException(
            "Audit metadata must be a dict.",
            details={"type": type(metadata).__name__},
        )

    _validate_level(metadata, depth=1)
    return metadata


def _validate_level(value: dict, depth: int) -> None:
    if len(value) > MAX_KEYS_PER_LEVEL:
        raise UnsafeAuditMetadataException(
            "Audit metadata exceeds the maximum number of keys.",
            details={"max_keys": MAX_KEYS_PER_LEVEL, "actual": len(value)},
        )

    for key, item in value.items():
        _validate_key(key)
        _validate_value(item, depth=depth)


def _validate_key(key: object) -> None:
    if not isinstance(key, str):
        raise UnsafeAuditMetadataException(
            "Audit metadata keys must be strings.",
            details={"key_type": type(key).__name__},
        )
    if len(key) > MAX_KEY_LENGTH:
        raise UnsafeAuditMetadataException(
            "Audit metadata key exceeds the maximum length.",
            details={"max_key_length": MAX_KEY_LENGTH},
        )
    normalized = key.strip().lower().replace("-", "_")
    if normalized in _FORBIDDEN_KEYS:
        raise UnsafeAuditMetadataException(
            "Audit metadata contains a forbidden sensitive key.",
            details={"key": key},
        )


def _validate_value(value: object, depth: int) -> None:
    if isinstance(value, str):
        if len(value) > MAX_STRING_VALUE_LENGTH:
            raise UnsafeAuditMetadataException(
                "Audit metadata string value exceeds the maximum length.",
                details={"max_length": MAX_STRING_VALUE_LENGTH},
            )
        return

    if isinstance(value, (int, float)) or value is None:
        return

    if isinstance(value, dict):
        if depth >= MAX_NESTING_DEPTH:
            raise UnsafeAuditMetadataException(
                "Audit metadata exceeds the maximum nesting depth.",
                details={"max_depth": MAX_NESTING_DEPTH},
            )
        _validate_level(value, depth=depth + 1)
        return

    raise UnsafeAuditMetadataException(
        "Audit metadata contains an unsupported value type.",
        details={"type": type(value).__name__},
    )
